audit_header: false
title: Westside Real Estate Video Blog with Megan Silva
description: Our mission at Keller Williams is to be your best resource for Santa Monica real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Keller Williams Santa Monica, your professional Santa Monica Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Megan Silva
  title:
  license_number:
  about_markdown: |
    Megan’s specialization in the field of private wealth management focused on the family needs planning and lifestyle management of her entertainment industry and C-suite executive clients. Frequently she was tasked with finding and negotiating real estate deals for personal and/or investment purposes for her clients, and quite often the very high-profile and public image of these individuals required Megan to represent them with complete discretion in executing purchases and sales of multi-million-dollar transactions. Naturally, she found that her services to these clients in the real estate world could be a successful standalone business, and in founding an independent real estate practice she could better and more effectively serve the needs of her clientele while continuing to collaborate with her network in the finance, tax, and estate planning industries to enhance the overall wealth profile and resources of her client base.

    Representing her clients in over a billion dollars of transactions during her tenure in this field, Megan still maintains that her greatest professional accomplishment comes not as much from the high cumulative value of transactions she has completed, but rather from the immeasurable sense of joy her clients and their families have expressed to her when she calls them and says, “we did it – congratulations!”
  brand:
  brokerage: Keller Williams Santa Monica
  market: Westside
  address: 2701 Ocean Park Blvd, Suite 140, Santa Monica, CA 90405
  phone: 310-614-6513
  phone_type:
  phone2:
  phone2_type:
  email: Megan@megansilva.com
  url: http://megansilva.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Westside Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Westside Home?"
    CTA_text2: "Search the entire MLS for your Westside home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: true
  facebook_url:
  linkedin_url: https://www.linkedin.com/in/meganesilva/
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/megan7204/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Santa Monica Real Estate Podcast with Megan Silva'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Santa Monica Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Keller Williams Santa Monica - your professional Santa Monica Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Santa Monica, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Megan Silva'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: 
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#b40101'
  theme_color: '#4d4d4f'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#b40101'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
